App/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using App.Areas.Identity.Data;
using App.Entities;
using System.IO.Compression;
using App.Models;

namespace App.Web.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var eventList = new List<EventModel>();
            var events = await _context.Events.ToListAsync();
            foreach (var item in events)
            {
                eventList.Add(new EventModel
                {
                    EventID = item.EventID,
                    ClosureDate = item.ClosureDate,
                    EventDecription = item.EventDecription,
                    EventName = item.EventName,
                    OpenDate = item.OpenDate,
                    Posts = item.Posts,
                    preClosureDate = item.preClosureDate,
                    HoursRemain = (item.ClosureDate - DateTime.Now).TotalDays
                });
            }
            return _context.Events != null ? 
                          View(eventList) :
                          Problem("Entity set 'ApplicationDbContext.Events'  is null.");
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.Include(p=>p.Posts)
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventID,EventName,EventDecription,OpenDate,preClosureDate,ClosureDate")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventID,EventName,EventDecription,OpenDate,preClosureDate,ClosureDate")] Event @event)
        {
            if (id != @event.EventID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Events'  is null.");
            }
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return (_context.Events?.Any(e => e.EventID == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> DownloadAsZip(int eventId)
        {
            // Get the event and its posts from the database
            var eventEntity = _context.Events
                .Include(e => e.Posts)
                .FirstOrDefault(e => e.EventID == eventId);

            if (eventEntity == null)
            {
                return NotFound();
            }

            // Create a temporary folder to store the idea files
            var tempFolderPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempFolderPath);

            // Save each idea as a separate text file in the temporary folder
            foreach (var post in eventEntity.Posts)
            {
                var postContent = $"Title: {post.Title}\n" +
                  $"Brief: {post.Brief}\n" +
                  $"View: {post.View}\n" +
                  $"Like: {post.Like}\n" +
                  $"Dislike: {post.Dislike}\n";

                // Write the post content to a text file
                var postFilePath = Path.Combine(tempFolderPath, $"{post.Title}.txt");
                System.IO.File.WriteAllText(postFilePath, postContent);
            }

            // Create a ZIP archive from the temporary folder
            var zipFileName = $"{eventEntity.EventName}.zip";
            var zipFilePath = Path.Combine(Path.GetTempPath(), zipFileName);
            ZipFile.CreateFromDirectory(tempFolderPath, zipFilePath);

            // Return the ZIP file for download
            var fileBytes = System.IO.File.ReadAllBytes(zipFilePath);
            var contentType = "application/zip";
            var fileContentResult = new FileContentResult(fileBytes, contentType)
            {
                FileDownloadName = zipFileName
            };

            // Clean up the temporary folder and ZIP file
            Directory.Delete(tempFolderPath, true);
            System.IO.File.Delete(zipFilePath);

            return fileContentResult;
        }

        public async Task<IActionResult> DownloadAsExcel(int eventId)
        {
            // Get the event and its posts from the database
            var eventEntity = _context.Events
                .Include(e => e.Posts)
                .FirstOrDefault(e => e.EventID == eventId);

            if (eventEntity == null)
            {
                return NotFound();
            }

            // Create a new Excel workbook and worksheet
            var workbook = new ClosedXML.Excel.XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Posts");

            // Set the column headers
            worksheet.Cell(1, 1).Value = "Title";
            worksheet.Cell(1, 2).Value = "Brief";
            worksheet.Cell(1, 3).Value = "View";
            worksheet.Cell(1, 4).Value = "Like";
            worksheet.Cell(1, 5).Value = "Dislike";

            // Populate the worksheet with the data from the event's posts
            for (int i = 0; i < eventEntity.Posts.Count; i++)
            {
                var post = eventEntity.Posts[i];
                worksheet.Cell(i + 2, 1).Value = post.Title;
                worksheet.Cell(i + 2, 2).Value = post.Brief;
                worksheet.Cell(i + 2, 3).Value = post.View;
                worksheet.Cell(i + 2, 4).Value = post.Like;
                worksheet.Cell(i + 2, 5).Value = post.Dislike;
            }

            // Set the response headers to indicate that the response should be an Excel file
            var contentDisposition = new System.Net.Mime.ContentDisposition
            {
                FileName = $"{eventEntity.EventName}.xlsx",
                Inline = false
            };
            Response.Headers.Add("Content-Disposition", contentDisposition.ToString());
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            // Write the Excel file to the response stream
            using (var stream = new MemoryStream())
            {
                workbook.SaveAs(stream);
                stream.Seek(0, SeekOrigin.Begin);
                await stream.CopyToAsync(Response.Body);
            }

            return new EmptyResult();
        }

    }
}

App/Controllers/UsersController.cs
using App.Areas.Identity.Data;
using App.Core;
using App.Models;
using App.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace App.Web.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IToastNotification _toastNotification;
        public UsersController(
            ApplicationDbContext context, 
            UserManager<User> userManager,
            IToastNotification toastNotification)
        {
            _context = context;
            _userManager = userManager;
            _toastNotification = toastNotification;
        }
        [Authorize(Roles = $"{nameof(Enums.Roles.Admin)},{nameof(Enums.Roles.Manager)}")]
        public IActionResult Index()
        {
            var data = _context.Users.ToList();
            return View(data);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddUserViewModel model)
        {
            try
            {
                var newUser = new User
                {
                    Firstname = model.Firstname,
                    Lastname = model.Lastname,
                    Email = model.Email,
                    UserName = model.Email,
                    Genre = model.Genre,
                    EmailConfirmed = true,
                    PhoneNumberConfirmed = true
                };
                await _userManager.CreateAsync(newUser, model.Pwd);
                _toastNotification.AddSuccessToastMessage($"Create a user {newUser.Email} successfully!");
            }
            catch (Exception e)
            {

                _toastNotification.AddErrorToastMessage("Create a user was failed!");
            }
            
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(string Id)
        {
            //here, get the users from the database in the real application

            //getting a user from collection for demo purpose
            var user = await _context.Users.Where(s => s.Id == Id).FirstOrDefaultAsync();
            if (user == null)
            {
                return RedirectToAction("Index");
            }
            var roles = await _context.Roles.ToListAsync();

            var userRoles = await _context.UserRoles.Where(x => x.UserId == user.Id).ToListAsync();

            var roleItems = roles.Select(s =>
                new SelectListItem(s.Name, s.Id, userRoles.Any(a => a.RoleId.Contains(s.Id)))).ToList();
            var viewModel = new EditUserViewModel
            {
                User = user,
                Roles = roleItems
            };

            return View(viewModel);
        }

        public ActionResult Delete(string Id)
        {
            //here, get the users from the database in the real application

            //getting a user from collection for demo purpose
            var existuser = _context.Users.FirstOrDefault(s => s.Id == Id);
            if (existuser != null)
            {
                _context.Users.Remove(existuser);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Edit(EditUserViewModel model)
        {
            try
            {
                //update user in DB using EntityFramework in real-life application

                //update list by removing old user and adding updated user for demo purpose
                var existuser = _context.Users.FirstOrDefault(s => s.Id == model.User.Id);
                if (existuser != null)
                {
                    existuser.Firstname = model.User.Firstname;
                    existuser.Lastname = model.User.Lastname;
                    _context.Users.Update(existuser);

                    var userroles = await _context.UserRoles.Where(x => x.UserId == existuser.Id).ToListAsync();
                    var rolesToAdd = new List<string>();
                    var rolesToDelete = new List<string>();


                    foreach (var role in model.Roles)
                    {
                        var assignedRole = userroles.FirstOrDefault(x => x.RoleId == role.Value);
                        if (role.Selected)
                        {
                            if (assignedRole == null)
                            {
                                rolesToAdd.Add(role.Text);
                            }
                        }
                        else
                        {
                            if (assignedRole != null)
                            {
                                rolesToDelete.Add(role.Text);
                            }
                        }
                    }
                    if (rolesToAdd.Any())
                    {
                        await _userManager.AddToRolesAsync(existuser, rolesToAdd);
                    }
                    if (rolesToDelete.Any())
                    {
                        await _userManager.RemoveFromRolesAsync(existuser, rolesToDelete);
                    }
                    _context.SaveChanges();
                    _toastNotification.AddSuccessToastMessage("Save Role successfully!");
                }
            }
            catch (Exception e)
            {

                _toastNotification.AddErrorToastMessage("Save Role was failed");
            }

            return RedirectToAction("Index");
        }
    }
}

App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Greenwich Ideas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #E8e4d0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Greenwich Ideas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav nav-tabs flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear-wide-connected"></i>
                                    Management
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="Index"><i class="bi bi-people"></i> User</a>
                                    <a class="dropdown-item" asp-controller="Departments" asp-action="Index"><i class="bi bi-person-fill-gear"></i> Department</a>
                                    <a class="dropdown-item" asp-controller="Categories" asp-action="Index"><i class="bi bi-person-fill-gear"></i> Category</a>
                                    <a class="dropdown-item" asp-controller="AdminSubmission" asp-action="Index"><i class="bi bi-person-fill-gear"></i> Submission</a>
                                    <a class="dropdown-item" asp-controller="Home" asp-action="Statics"><i class="bi bi-person-fill-gear"></i> Statics</a>

                                    @*<a class="dropdown-item" asp-controller="Statics" asp-action="Index"><i class="bi bi-person-fill-gear"></i> Statics</a>*@


                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index"><i class="bi bi-gear-wide-connected"></i> Staff Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-shield-check"></i> About Us</a>
                        </li>

                    </ul>
                </div>
                <partial name="_loginPartial"></partial>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Greenwich Ideas - <a asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>