App/Entities/Department.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace App.Entities
{
    public class Department
    {
        //TODO: Add key
        //
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DepartmentID { get; set; }
        [Display(Name = "Department Name")]
        public string? DepartmentName { get; set; }
    }
}

App/Controllers/DepartmentsController.cs
using App.Areas.Identity.Data;
using App.Entities;
using App.Models;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace App.Web.Controllers
{

    //TODO: Create DepartmentController
    //TODO: Create Models in Models folder
    //TODO: Create Views (refer the Users Page)

    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        //private readonly IToastNotification _toastNotification;
        public DepartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var data = _context.Departments.AsAsyncEnumerable();
            return View(data);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddDepartmentView context)
        {
            try
            {
                var newDepartment = new Department
                {
                    
                    DepartmentName = context.DepartmentName

                };
                _context.Departments.Add(newDepartment);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int Id)
        {
            //here, get the roles from the database in the real application

            //getting a role from collection for demo purpose

            var depart = _context.Departments.Where(x => x.DepartmentID == Id).FirstOrDefault();

            return View(depart);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Department department)
        {
            //update role in DB using EntityFramework in real-life application

            var departt = _context.Departments.Where(x => x.DepartmentID == department.DepartmentID).FirstOrDefault();

 
            departt.DepartmentName = department.DepartmentName;

            _context.Departments.Update(departt);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var @depart = await _context.Departments
                .FirstOrDefaultAsync(m => m.DepartmentID == id);
            if (@depart == null)
            {
                return NotFound();
            }

            return View(@depart);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Departments'  is null.");
            }
            var @depart = await _context.Departments.FindAsync(id);
            if (@depart != null)
            {
                _context.Departments.Remove(@depart);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

App/Views/Departments/Create.cshtml
@model App.Models.AddDepartmentView

@{
    ViewData["Title"] = "Create a new Department";
}
<body style="background-color: #FDFCF6">

    <h1 class="text-center">Create a new Department</h1>
    <hr />

    <div class="row">
        <div class="col-md-9">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="DepartmentName" class="control-label"></label>
                    <input asp-for="DepartmentName" class="form-control" />
                    <span asp-validation-for="DepartmentName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save A New department" class="btn btn-secondary" />
                </div>
                <b>@ViewBag.message</b>
            </form>
        </div>
    </div>
</body>

App/Views/Departments/Delete.cshtml
@model App.Entities.Department

@{
    ViewData["Title"] = "Delete";
}
<body style="background-color: #FDFCF6">

    <h1 class="text-center">Delete</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Event</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DepartmentName)
            </dt>


        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="DepartmentID" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>
    </div>
</body>

App/Views/Departments/Edit.cshtml
@model App.Entities.Department

@{
    ViewData["Title"] = "Edit";
}
<body style="background-color: #FDFCF6">

    <h1 class="text-center">Edit</h1>

    <h4>Event</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DepartmentID" />
                <div class="form-group">
                    <label asp-for="DepartmentName" class="control-label"></label>
                    <input asp-for="DepartmentName" class="form-control" />
                    <span asp-validation-for="DepartmentName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-secondary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

App/Views/Departments/Index.cshtml
@model IEnumerable<App.Entities.Department>


@{
    ViewData["Title"] = "Department";

}


<body style="background-color: #FDFCF6">

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class=text-center>Deparment Management</h1>
            <div class="d-flex align-items-end justify-content-start">
                <div>
                    <a class="btn btn-secondary" href="@Url.ActionLink("Create", "Departments")"><i class="bi bi-plus-circle-fill"></i> Create A New</a>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.DepartmentName)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="align-middle">@Html.DisplayFor(modelItem => item.DepartmentName)</td>
                            <td class="align-middle">
                                <a class="btn btn-outline-secondary" href="@Url.ActionLink("Edit", "Departments", new { id= item.DepartmentID })"><i class="bi bi-pen"></i> Edit</a>
                                <a class="btn btn-danger" href="@Url.ActionLink("Delete", "Departments", new { id= item.DepartmentID })"><i class="bi bi-eye"></i> Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>